###################### GNSS ######################
# BASE POINT for ENU coordinate frame
# UNIST
# local_long            : 35.571127
# local_lat             : 129.1874088
# local_alt             : 76.716
# Daugu PG
local_long            : 35.6475476
local_lat             : 128.4026479
local_alt             : 48.827

topic_gnss     : /gnss_1/llh_position
gnss_x_imuFrame      : 0.0
gnss_y_imuFrame      : 0.0
gnss_z_imuFrame      : 0.0


###################### IMU ######################
topic_imu             : /imu/data
acc_noise             : 0.01
gyr_noise             : 0.0001
acc_bias_noise        : 0.000001
gyr_bias_noise        : 0.00000001


###################### INITIALIZATION ######################
kGnssBufSize          : 100   # (Hz x sec)  eg. 100Hz x 1sec
ImuBufSize            : 5     # (Hz x sec)  eg. 2hz   x 2.5secs
acc_std_threshold     : 0.1
heading_std_threshold : 0.1
delta_gnss_threshold  : 0.05
time_sync_threshold   : 0.05
###################### ODOMETRY ######################
# transformation for base_link 
baes_link_x_imuFrame      : 0.0
baes_link_y_imuFrame      : 0.0
baes_link_z_imuFrame      : 0.0
baes_link_qx_imuFrame     : 0.0
baes_link_qy_imuFrame     : 0.0
baes_link_qz_imuFrame     : 0.0
baes_link_qw_imuFrame     : 1.0





