###################### GNSS ######################
gnss_f_x_imuFrame         : 1.47
gnss_f_y_imuFrame         : 0.0
gnss_f_z_imuFrame         : 0.0

gnss_b_x_imuFrame         : 0.0
gnss_b_y_imuFrame         : 0.0
gnss_b_z_imuFrame         : 0.0

###################### IMU for KF ######################
acc_noise                 : 0.01
gyr_noise                 : 0.0001
acc_bias_noise            : 0.000001
gyr_bias_noise            : 0.00000001

###################### INITIALIZATION ######################
DelayImuBufSize           : 18   # (Hz x sec)  eg. 100Hz x 0.2sec

###################### INITIALIZATION ######################
InitImuBufSize                : 100   # (Hz x sec)  eg. 100Hz x 1sec
GnssBufSize               : 5     # (Hz x sec)  eg. 2hz   x 2.5secs
acc_std_threshold         : 0.1
heading_std_threshold     : 0.1
delta_gnss_threshold      : 0.05
time_sync_threshold       : 0.05

###################### PUB ODOMETRY ######################
topic_odometry            : /eskf/odom
# transformation for base_link 
baes_link_x_imuFrame      : 0.0
baes_link_y_imuFrame      : 0.0
baes_link_z_imuFrame      : 0.0
baes_link_qx_imuFrame     : 0.0
baes_link_qy_imuFrame     : 0.0
baes_link_qz_imuFrame     : 0.0
baes_link_qw_imuFrame     : 1.0

###################### TF ######################
pub_tf                   : false
frame_id             : map_gnss
# child_frame_id            : base_link

###################### OTHERS ######################
topic_path                : /eskf/path
pub_path                  : false


