###################### GNSS ######################
topic_gnss_front          : /gnss_2/llh_position
topic_gnss_behind         : /gnss_1/llh_position

###################### IMU ######################
topic_imu                 : /imu/data

###################### ODOMETRY ######################
topic_odometry            : /eskf/odom

###################### TF ######################
pub_tf_eskf                    : false
frame_id_eskf               : map_gnss
child_frame_id            : base_link

###################### OTHERS ######################
topic_path                : /eskf/path
pub_path                  : false


